### ISSUE TITLE
Feature: remove useless species.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-api#444] opened 2020-11-03 02:09 UTC
Should be able to remove wrong or useless species. 

In the DB, should set active to false to remove them, rather than delete the recode from DB.

**Comment by nmcharlton** [comment] 2020-12-06 11:14
We should only allow the user to remove species with no trees allocated.
We'll need to set `active` on all the existing species to `true` when we roll this out.

**Comment by nmcharlton** [comment] 2021-02-28 21:30
This issue depends on Greenstand/treetracker-database#63

**Comment by nmcharlton** [comment] 2021-04-07 19:12
Duplicate of #486

**Closed as completed by nmcharlton** 2021-04-07 19:12 UTC
Labels: good first issue, tool: Species
