### ISSUE TITLE
Can not delete species.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-api#486] opened 2021-01-04 07:54 UTC
Reproduce: 

1. Open test.admin.treetracker.org 
2. Go to the species page
3. Find one species which's tagged count is zero.
4. Click 'delete', click 'confirm'
5. Doesn't work.

The request is complaining `500` error:

<img width="1552" alt="Screen Shot 2021-01-04 at 3 51 08 PM" src="https://user-images.githubusercontent.com/5744708/103513212-1becb480-4ea5-11eb-8009-e1e069ef7273.png">

**Comment by nmcharlton** [comment] 2021-01-06 21:21
Likely duplicate of #444

**Comment by luacmartins** [comment] 2021-02-08 16:43
This functionality seems to be working in my local environment, but not on test.admin.treetracker.org as mentioned. What are the differences between both environments?

**Comment by nmcharlton** [comment] 2021-02-08 17:18
> This functionality seems to be working in my local environment, but not on test.admin.treetracker.org as mentioned. What are the differences between both environments?

@luacmartins The DB policy in test and production prohibits `delete` instructions. Instead, we have an `active` column in all tables that is used to mark items as deleted. The front end should never show anything that is inactive.

See #444

**Comment by nmcharlton** [comment] 2021-02-28 21:30
This issue depends on Greenstand/treetracker-database#63

**Comment by nmcharlton** [comment] 2021-04-07 19:13
Fixed in #530

**Closed as completed by nmcharlton** 2021-04-07 19:13 UTC
Labels: type: bug, duplicate, good first issue, tool: Species
