### ISSUE TITLE
Planter search/filter first_name not working correctly (case sensitive?)

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-api#552] opened 2021-04-20 09:34 UTC
Go to planter and search (in live system) for Deepak. Can not find planter id 3571 (his first name is Deepak). His name is in the database with "deepak" but it shows Deepak on the webmap https://map.treetracker.org/?userid=3571

**Comment by nmcharlton** [comment] 2021-04-20 09:45
@sebastiangaertner This appears to be identical to Greenstand/treetracker-admin-client#72
I've suggested we make the search case-insensitive, but we may also want to change the way we display names across the board to match the formatting in the database.

If we're getting lots of names coming through from the Treetracker app in all lowercase, I'd suggest we should apply auto-capitalisation in the app inputs.

**Comment by nmcharlton** [comment] 2021-04-20 16:41
Duplicate of Greenstand/treetracker-admin-client#72

**Closed as completed by nmcharlton** 2021-04-20 16:41 UTC
Labels: duplicate
