### ISSUE TITLE
System user roles getting repeatedly listed 

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-api#417] opened 2020-09-29 07:01 UTC
![Screenshot 2020-09-27 at 21 00 29](https://user-images.githubusercontent.com/3283800/94523694-dd09eb80-0231-11eb-8e49-93dae699f7fc.png)

**Comment by nmcharlton** [comment] 2020-09-29 18:53
Duplicate of #369

**Comment by nmcharlton** [comment] 2020-10-22 14:43
This is fixed on the `master` branch but has not yet been merged into `test_release` and deployed.

**Comment by nmcharlton** [comment] 2021-01-09 16:32
Fixed released (#463)

**Closed as completed by nmcharlton** 2021-01-09 16:32 UTC
Labels: type: bug, ready for test
